-- Insert 40 college entries into the college table

INSERT INTO college (id, college_name, branch, location) VALUES
(3, 'Indian Institute of Technology Madras', 'Mechanical Engineering', 'Chennai'),
(4, 'Indian Institute of Technology Kanpur', 'Civil Engineering', 'Kanpur'),
(5, 'Indian Institute of Technology Kharagpur', 'Electronics and Communication', 'Kharagpur'),
(6, 'Delhi Technological University', 'Information Technology', 'New Delhi'),
(7, 'Netaji Subhas University of Technology', 'Computer Science', 'New Delhi'),
(8, 'Birla Institute of Technology and Science', 'Computer Science', 'Pilani'),
(9, 'Vellore Institute of Technology', 'Electronics Engineering', 'Vellore'),
(10, 'Manipal Institute of Technology', 'Mechanical Engineering', 'Manipal'),
(11, 'National Institute of Technology Trichy', 'Computer Science', 'Tiruchirappalli'),
(12, 'National Institute of Technology Warangal', 'Electrical Engineering', 'Warangal'),
(13, 'National Institute of Technology Surathkal', 'Information Technology', 'Surathkal'),
(14, 'Anna University', 'Civil Engineering', 'Chennai'),
(15, 'Jadavpur University', 'Computer Science', 'Kolkata'),
(16, 'College of Engineering Pune', 'Mechanical Engineering', 'Pune'),
(17, 'PSG College of Technology', 'Electronics Engineering', 'Coimbatore'),
(18, 'Thiagarajar College of Engineering', 'Computer Science', 'Madurai'),
(19, 'SRM Institute of Science and Technology', 'Information Technology', 'Chennai'),
(20, 'Amity University', 'Computer Science', 'Noida'),
(21, 'Lovely Professional University', 'Computer Science and Engineering', 'Phagwara'),
(22, 'Thapar Institute of Engineering', 'Electronics Engineering', 'Patiala'),
(23, 'PES University', 'Computer Science', 'Bangalore'),
(24, 'RV College of Engineering', 'Information Science', 'Bangalore'),
(25, 'BMS College of Engineering', 'Electronics and Communication', 'Bangalore'),
(26, 'NIIT University', 'Computer Science', 'Neemrana'),
(27, 'Jamia Millia Islamia', 'Computer Engineering', 'New Delhi'),
(28, 'Aligarh Muslim University', 'Electrical Engineering', 'Aligarh'),
(29, 'Banaras Hindu University', 'Mechanical Engineering', 'Varanasi'),
(30, 'Osmania University', 'Computer Science', 'Hyderabad'),
(31, 'JNTU Hyderabad', 'Information Technology', 'Hyderabad'),
(32, 'Pune Institute of Computer Technology', 'Computer Engineering', 'Pune'),
(33, 'Veermata Jijabai Technological Institute', 'Electronics Engineering', 'Mumbai'),
(34, 'Institute of Chemical Technology', 'Chemical Engineering', 'Mumbai'),
(35, 'Sardar Patel Institute of Technology', 'Computer Engineering', 'Mumbai'),
(36, 'Dwarkadas J Sanghvi College of Engineering', 'Information Technology', 'Mumbai'),
(37, 'K J Somaiya College of Engineering', 'Electronics and Telecommunication', 'Mumbai'),
(38, 'Ramaiah Institute of Technology', 'Computer Science', 'Bangalore'),
(39, 'Dayananda Sagar College of Engineering', 'Information Science', 'Bangalore'),
(40, 'Christ University', 'Computer Science', 'Bangalore');
